PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRET_T_ARTICLE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRET_T_ARTICLE-ARTICLE_ID .
    FIELD ZRET_T_ARTICLE-ARTICLE_NAME .
    FIELD ZRET_T_ARTICLE-ARTICLE_TYPE .
    FIELD ZRET_T_ARTICLE-EAN .
    FIELD ZRET_T_ARTICLE-BASE_UOM .
    FIELD ZRET_T_ARTICLE-PRICE .
    FIELD ZRET_T_ARTICLE-CURRENCY .
    FIELD ZRET_T_ARTICLE-ACTIVE_FLAG .
    FIELD ZRET_T_ARTICLE-CREATED_BY .
    FIELD ZRET_T_ARTICLE-CREATED_ON .
    FIELD ZRET_T_ARTICLE-CHANGED_BY .
    FIELD ZRET_T_ARTICLE-CHANGED_ON .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRET_T_ARTICLE-ARTICLE_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
